// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAV6y6WQNjYAxZ0i6TxXkh-KLoTLTFok',
    appId: '1:818734402363:web:de46bfbdb8eabbfabe851e',
    messagingSenderId: '818734402363',
    projectId: 'flutterapp-90aa5',
    authDomain: 'flutterapp-90aa5.firebaseapp.com',
    storageBucket: 'flutterapp-90aa5.appspot.com',
    measurementId: 'G-YMCH7QM7W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwcc0xfc1sZ6RxG_YuH0lQqXodnr1zLn0',
    appId: '1:818734402363:android:88ad5d491075c252be851e',
    messagingSenderId: '818734402363',
    projectId: 'flutterapp-90aa5',
    storageBucket: 'flutterapp-90aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx-XOcvZ7VgJglQxO4AFJYKLoWvVH9Bks',
    appId: '1:818734402363:ios:2dd39d34dbfc9a24be851e',
    messagingSenderId: '818734402363',
    projectId: 'flutterapp-90aa5',
    storageBucket: 'flutterapp-90aa5.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx-XOcvZ7VgJglQxO4AFJYKLoWvVH9Bks',
    appId: '1:818734402363:ios:5afc985a20f09203be851e',
    messagingSenderId: '818734402363',
    projectId: 'flutterapp-90aa5',
    storageBucket: 'flutterapp-90aa5.appspot.com',
    iosBundleId: 'com.example.flutterproject.RunnerTests',
  );
}
